#!/usr/bin/env bash
# displays 'Best School' 10 times, but for the 9th one, displays 'Hi' after

i=1
while ((i <= 10)); do
    echo 'Best School'
    if [ $i = 9 ]; then
	echo 'Hi'
    fi
    ((i += 1))
done
