#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

hour=0
while ((hour <= 12)); do
    echo 'Hour:' $hour
    minute=1
    while ((minute < 60)); do
	echo $minute
	((minute += 1))
    done
    ((hour += 1))
done
